### ISSUE TITLE
Local repository doesn't update - Could not read Username

### ISSUE THREAD

**Issue by tarunsachdeva** [koppen/redmine_github_hook#35]
I'm getting the following error after github sends the POST with commit info. 

>   Current user: anonymous
> GithubHook: Command 'git --git-dir='/home/bitnami/repos/wattpad-redmine/wattpad-redmine.git' fetch origin' didn't exit properly. Full output: ["fatal: could not read Username for 'https://github.com': No such device or address\n"]

I can see the payload in the logs. Not sure how to get rid of this error, though.

**Comment by AlainLaroche** [comment]
Hi,
I have a similar problem with redmine 3.2.2 installed from docker. This version is using webrick instead of apache.
Before read your post, I had this in my log

> Current user: anonymous
> GithubHook: Command 'git fetch origin' didn't exit properly. Full output: ["Could not create directory '/home/redmine/.ssh'.\r\n", "Host key verification failed.\r\n", ...

Followed @skhani suggestions and created directories /home/redmine/.ssh, created ssh keys with 777 access rights and added in my github account.
Now I have the following logs:

> Current user: anonymous
> GithubHook: Command 'git fetch origin' didn't exit properly. Full output: ["Host key verification failed.\r\n", "fatal: Could not read from remote repository.\n", "\n", "Please make sure you have the correct access rights\n", "and the repository exists.\n"]
It seems that GithubHook is finding the ssh key but the host verification failed.

**Comment by sand1p** [comment]
@tarunsachdeva  Have you found any solution to this issue.Because when I configured my git commits were getting reflected but suddenly it stopped updating commits to redmine .
I received following logs .
###########
  Current user: anonymous
  GithubHook: Command 'git fetch origin' didn't exit properly. Full output: ["git: not found\n"]
##################

**Comment by sand1p** [comment]
someone please help

**Comment by tarunsachdeva** [comment]
Sorry - I haven't. Gave up on Redmine a while ago :(
