### ISSUE TITLE
Install fails with Redmine 2.3.4.stable

### ISSUE THREAD

**Issue by col-panic** [koppen/redmine_github_hook#69]
When installing I get an error starting redmine

```
There are no gemspecs at /home/server/services/redmine-2.3.4. (Bundler::InvalidOption)
  /home/server/services/redmine-2.3.4/Gemfile:95:in `instance_eval'
  (eval):4:in `block in eval_gemfile'
  /home/server/services/redmine-2.3.4/Gemfile:95:in `instance_eval'
  /home/server/services/redmine-2.3.4/Gemfile:95:in `block in eval_gemfile'
  /home/server/services/redmine-2.3.4/Gemfile:93:in `glob'
  /home/server/services/redmine-2.3.4/Gemfile:93:in `eval_gemfile'
  /var/lib/gems/1.9.1/gems/bundler-1.3.5/lib/bundler/dsl.rb:30:in `instance_eval'
  /var/lib/gems/1.9.1/gems/bundler-1.3.5/lib/bundler/dsl.rb:30:in `eval_gemfile'
  /var/lib/gems/1.9.1/gems/bundler-1.3.5/lib/bundler/dsl.rb:9:in `evaluate'
  /var/lib/gems/1.9.1/gems/bundler-1.3.5/lib/bundler/definition.rb:19:in `build'
  /var/lib/gems/1.9.1/gems/bundler-1.3.5/lib/bundler.rb:148:in `definition'
  /var/lib/gems/1.9.1/gems/bundler-1.3.5/lib/bundler.rb:116:in `setup'
  /var/lib/gems/1.9.1/gems/bundler-1.3.5/lib/bundler/setup.rb:17:in `<top (required)>'
  /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in `require'
  /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in `rescue in require'
  /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
  /var/lib/gems/1.9.1/gems/passenger-4.0.18/lib/phusion_passenger/loader_shared_helpers.rb:212:in `run_load_path_setup_code'
  /var/lib/gems/1.9.1/gems/passenger-4.0.18/helper-scripts/rack-preloader.rb:96:in `preload_app'
  /var/lib/gems/1.9.1/gems/passenger-4.0.18/helper-scripts/rack-preloader.rb:150:in `<module:App>'
  /var/lib/gems/1.9.1/gems/passenger-4.0.18/helper-scripts/rack-preloader.rb:29:in `<module:PhusionPassenger>'
  /var/lib/gems/1.9.1/gems/passenger-4.0.18/helper-scripts/rack-preloader.rb:28:in `<main>'
```

trying to install the dependencies fails with

```
root@myhost:/srv/services/redmine# bundle install --without development test
There are no gemspecs at /home/server/services/redmine-2.3.4.
```

**Comment by koppen** [comment]
Interesting, I don't see anything Redmine GitHub Hook specific in that stacktrace.

How did you install the hook? Are you using the plugin-based installation? Could you try the gem-based installation instead, does that change this?

**Comment by rudi** [comment]
I see the same, installed plugin-based via "git clone" and adjusted permissions.

**Comment by koppen** [comment]
Could you try the gem-based installation instead, does that change this?

**Comment by HStine** [comment]
Just passing by. I ran into the same problem and encountered this while searching for an answer.

Just wanted to say that, yes, this problem is resolved using the gem-based installation.

Took me awhile to figure it out because I was unfamiliar with the environment ruby (and redmine, by extension) uses, but the following steps appear to be a general overview of how it is done.

I apologize if the details are insultingly obvious to some people. I can only share what I needed to know. I use the same instructions that koppen included in his Readme.md, but include the details of how it played out for myself. I haven't dealt much with a ruby environment, so I imagine this stuff is obvious to those who have.

1. Install the redmine_github_hook into the ruby version that redmine uses, using the following command "gem install redmine_github_hook -v 2.0.0" (Important: If you have multiple versions of ruby on your machine make sure you run this command with the same version of ruby that redmine runs off of. My redmine used 1.9.1, but "ruby -v" returned "2.1.1" and various others each time I ran this command. I needed to switch over to 1.9.1 for this to effect redmine. This may be obvious to others, but it messed me up, so I am mentioning it for the few who are as ignorant as me.)

2. Open redmine's Gemfile. This file is located in redmine's root directory. For me, the path was /var/www/redmine/Gemfile. In this file add the line 'gem "redmine_github_hook"'.

3. Run the command "bundle" in the root directory of redmine.

4. Restart redmine. For me, this was done by restarting apache2 which was the server running redmine. I used the command "/etc/init.d/apache2 restart".


As an aside, the "There are no gemspecs at" error occurred so long as the git clone of the plugin was in my redmine "plugins" directory. I would see this error on two occasions. First, if I attempted to run "bundle" in the redmine root directory with the clone in "plugins". Second, I would get it in lieu of the redmine web-interface if I restarted redmine with the clone in there.
