### ISSUE TITLE
What about multiple repos with different deploy keys?

### ISSUE THREAD

**Issue by poige** [koppen/redmine_github_hook#74]
(Not really a bug report, just a request for clarification.)

– As it turns out you can't have same deploy key for different repos with Github, so is that handled in a way in the plugin? Couldn't find it anywhere in description.

**Comment by koppen** [comment]
Redmine GitHub Hook makes no assumptions about permissions, this is all handled by Gits transport(?)layer, in most cases SSH. Basically, if git pull works from the commandline, Redmine Github Hook should work.

Can you not just have multiple deploy keys for the user running Redmine, one for each repository?

Alternatively, you could add a Redmine-specific SSH key to a real GitHub user with access to the repositories.

**Comment by poige** [comment]
The problem is you can't have *same* key for different Github's repos.

**Comment by koppen** [comment]
Redmine Github Hook does nothing directly with keys or permissions or what restrictions GitHub puts on deployment keys.

What I have done, personally, is to generate a key for my Redmine user, and then add that key as part of my own SSH keys on GitHub. This way the Redmine user has access to all my repositories.

You might be able to use https access rather than ssh, though, and use something like http://git-scm.com/docs/gitcredentials to get around the password prompt, but I am guessing here.

Let me know how it works out for you, sorry I can't be of much help.

**Comment by poige** [comment]
Once again: you can't have same **deployment** key for different repos. It means you need a way to load-use proper key when fetching changesets from GitHub. I didn't look into sources of your plugin, but since it's not cofigurable, I don't see how can one make it use different keys.
