### ISSUE TITLE
Use Github hook with daemon running Redmine

### ISSUE THREAD

**Issue by renkazan** [koppen/redmine_github_hook#84]
Hello, I am using Redmine on a Bitnami VM and the user running Redmine is `daemon`. So I cannot configure SSH keys for it. 
Is there a way to configure this plugin to run git command with another user ? 

For information the plugin gives me this error :

> Current user: anonymous
  GithubHook: Command 'git fetch origin' didn't exit properly. Full output: ["Permission denied, please try again.\r\n", "Permission denied, please try again.\r\n", "Permission denied (publickey,password).\r\n", "fatal: Could not read from remote repository.\n", "\n", "Please make sure you have the correct access rights\n", "and the repository exists.\n"]
  GithubHook: Redmine repository updated: ad-socleapplicationsmetier (Git: 172.0ms, Redmine: 39.3ms)

Thanks in advance for your help.

**Comment by koppen** [comment]
There is currently no way to configure the plugin to run as a different user. Also, I'm not entirely sure how we'd go about it, but that might just be my Linux-skills failing me.

There has previously been some discussion around this at https://github.com/koppen/redmine_github_hook/issues/40, not sure anything solid came of it.

You might be able to get somewhere using HTTPS instead of SSH, but I'm not entirely sure how that'd pan out.

**Comment by renkazan** [comment]
I finally found a solution, my user had no home and no bash. I modified the file `/etc/passwd` and set a home and a bash, and it works. I just hope that it will not change the behavior of Redmine.
Thanks for your reply.
