### ISSUE TITLE
Tags deleted in the remote repository are not deleted from the local repository

### ISSUE THREAD

**Issue by takamat30** [koppen/redmine_github_hook#91]
The following git command cleans up the branch. However, the tag will not be cleaned up.

    fetch --prune origin "+refs/heads/*:refs/heads/*"

Can you fix the plugin so that you can clean up the tags?

**Comment by koppen** [comment]
Thanks for the suggestion, I would definitely look at merging a pull request containing a change that does what you want.

**Comment by djbrown** [comment]
a simple fix for that would be adding [`--prune-tags`](https://git-scm.com/docs/git-fetch#Documentation/git-fetch.txt---prune-tags) to `git fetch --prune` 

I would prefer [`git remote update --prune`](https://git-scm.com/docs/git-remote#Documentation/git-remote.txt-emupdateem) though, since that already updates all refs.

**Comment by koppen** [comment]
Sounds good to me @djbrown, thanks for the suggestion. If this works equally well with bare and non-bare repositories I would definitely look at merging a pull request containing that change.

**Comment by djbrown** [comment]
Actually I have to correct myself: there's no need to use `git remote update`.
See [Differences between git remote update and fetch? - Stack Overflow](https://stackoverflow.com/questions/1856499/differences-between-git-remote-update-and-fetch/17512004#17512004)
