### ISSUE TITLE
Support for Redmine 4.x

### ISSUE THREAD

**Issue by Cmon169** [koppen/redmine_github_hook#97]
May I ask if redmine github hook supports Redmine 4.x?
The plugin loaded and is listed under Administration >> Plugins, but I don't see the it under Roles >> Permissions Report.
I have checked the production.log file but it didn't mention anything about the plugin.

I have followed the instruction:
1) add the line gem 'redmine_git_hook' in the Gemfile
2) Bundle install
3)  Restart apache2

I have tried with both installation but none of the worked.
Environment:
  Redmine version                4.0.6.stable
  Ruby version                   2.7.0-p0 (2019-12-25) [x86_64-linux-gnu]
  Rails version                  5.2.3
  Environment                    production
 
Environment:
 (bitnami) Redmine version                4.2.3.stable
  Ruby version                   2.6.9-p207 (2021-11-24) [x64-mingw32]
  Rails version                  5.2.6
  Environment                    production

Thanks.

**Comment by koppen** [comment]
Others have reported issues getting the plugin running, although I don't know if that was Redmine 4 specific, in https://github.com/koppen/redmine_github_hook/pull/94.

You might have better luck if you run the migrations as well:

 > Run migrations: `bundle exec rake redmine:plugins:migrate RAILS_ENV=production`

**Comment by Cmon169** [comment]
Thanks for replying.
I tried migration on both but not getting any luck.
After running migration it says it is using redmine_github_hook 3.0.1 on both.
Again no complain about that from the production.log.
I guess this will be one of the things that will have to wait then.

Thanks again for helping.

**Comment by koppen** [comment]
If you issue a POST request to /github_hook, what happens? Does it show up in the logfile?

**Comment by Cmon169** [comment]
The log from Github comes back with:
Headers
Content-Length: 196
Content-Type: text/html; charset=iso-8859-1
Date: Fri, 15 Apr 2022 05:15:36 GMT
Server: Apache
X-Frame-Options: SAMEORIGIN

Body
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
</body></html>

The apache2 log gives:
140.82.115.144 - - [15/Apr/2022:01:12:32 -0400] "POST /github_hook?project_ID=12 HTTP/1.1" 404 196
140.82.115.145 - - [15/Apr/2022:01:15:36 -0400] "POST /github_hook HTTP/1.1" 404 196
140.82.115.148 - - [15/Apr/2022:01:18:16 -0400] "POST /github_hook HTTP/1.1" 404 196

I am new to Redmine and I am not quite sure how to debug the problem.
The application(s) are installed on Windows VMs.
Judging by the above maybe apache doesn't know how to respond to the POST request?

**Comment by koppen** [comment]
It's been a while since I debugged anything with Redmine, so bear with me here...

1. If the plugin is installed correctly, sending a GET request to /github_hook (just using your browser), should render an [installation confirmation](https://github.com/koppen/redmine_github_hook/blob/main/app/views/github_hook/welcome.html.erb).
2. When POSTing from GitHub, the URL should include the identifier of your project, which is likely a string (IIRC the same string as is seen in the URL of your Redmine installation). In other words, I'd suspect something like `project_name` instead of `12` in the first request.
3. The parameter for the project identifier is `project_id`, not `project_ID` - the case of the characters matter.

Outside of that I don't know what you could do, and it's likely that Redmine 4 just isn't compatible, sorry.

**Comment by Cmon169** [comment]
Hi thanks for the suggestion.
I've tried the above and it still comes back with the 404 error.
I guess it is just not able to work with Redmine 4 then.

Thanks for your time help me out.
